import fs from 'fs';

const ca = {
    'app.title': 'Preguntador',
    'app.subtitle': 'Crea els teus quizzes i juga en temps real amb amics',
    'app.pageTitle': 'Preguntador | Quiz en viu',
    'app.pageDescription': 'Joc de quiz en temps real sense backend. Crea preguntes i juga amb amics.',
    'app.repository': 'Repositori',
    'language.es': 'Espanyol',
    'language.en': 'Anglès',
    'language.gl': 'Gallec',
    'language.fr': 'Francès',
    'language.de': 'Alemany',
    'language.pt': 'Portuguès',
    'language.ca': 'Català',
    'language.eu': 'Basc',
    'home.createQuiz': '✏️ Crear nou quiz',
    'home.importQuiz': '📥 Importar quiz',
    'home.joinGame': '🎮 Unir-se a una partida',
    'home.myQuizzes': '📚 Els meus quizzes',
    'home.questions': 'preguntes',
    'home.question': 'pregunta',
    'home.play': 'Jugar',
    'home.edit': 'Editar',
    'home.export': 'Exportar',
    'home.delete': 'Eliminar',
    'home.deleteConfirm': 'Eliminar aquest quiz?',
    'home.importError': 'No s\\'ha pogut importar. Assegura\\'t que el JSON és vàlid.',
    'home.chatgptPrompt': 'Generar amb IA',
    'home.invalidQuizTitle': 'Completa el quiz abans de jugar',
    'home.aiTitle': 'Generar amb IA',
    'home.aiStep1': '1. Copia i demana a la IA un nou quiz.',
    'home.aiStep2': '2. Enganxa aquí el JSON de resposta:',
    'home.aiCopy': '📋 Copiar',
    'home.aiCopied': '✅ Copiat',
    'home.aiCreate': '✨ Crear quiz',
    'home.aiPlaceholder': '{"title": "Nou Quiz", "questions": [...]}',
    'home.aiJsonError': 'El JSON és invàlid.',
    'home.aiPromptTemplate': `Actua com a creador de quizzes. Genera un JSON amb aquest tema: [TEMA_AQUI]. Regles... \n{  "title": "Títol",  "questions": [ { "text": "...", "timeLimit": 20, "image": "", "answers": [ { "text": "Opcio", "correct": false }, { "text": "Corr", "correct": true } ] } ] }`,
    'join.title': 'Unir-se',
    'join.codeLabel': 'Codi de sala',
    'join.nameLabel': 'El teu nom',
    'join.codePlaceholder': 'ABC123',
    'join.namePlaceholder': 'El teu nom',
    'join.connecting': '⏳ Connectant...',
    'join.connected': 'Connectat!',
    'join.joinBtn': '🚀 Unir-se',
    'join.backBtn': '← Tornar',
    'join.errorPrefix': 'Error',
    'join.errorInvalidCode': 'No s\\'ha pogut connectar.',
    'join.errorRejected': 'Rebutjat.',
    'join.errorGameInProgress': 'La partida ja ha començat.',
    'join.errorConnectionClosed': 'Connexió tancada.',
    'join.errorTimeout': 'Temps esgotat.',
    'join.errorUnknown': 'Error desconegut.',
    'lobby.roomCode': 'Codi de sala',
    'lobby.players': 'Jugadors',
    'lobby.waiting': 'Esperant...',
    'lobby.startBtn': '▶ Iniciar',
    'lobby.backBtn': '← Sortir',
    'lobby.joinHint': 'Escaneja per unir-te: {url}',
    'lobby.errorMissingQuiz': 'Quiz no trobat.',
    'lobby.errorInvalidQuiz': 'Quiz incomplet.',
    'lobby.errorGeneric': 'Error',
    'game.ready': 'Preparats...',
    'game.go': 'Ja!',
    'game.answers': 'respostes',
    'game.results': 'Resultats',
    'game.points': 'punts',
    'game.next': 'Següent →',
    'game.finalResults': 'Resultats finals',
    'game.nextQuestion': 'Següent pregunta →',
    'game.questionCounter': 'Pregunta {current} / {total}',
    'game.questionImageAlt': 'Imatge',
    'player.disconnectedTitle': 'Desconnectat',
    'player.disconnectedSub': 'S\\'ha perdut la connexió',
    'player.in': 'Estàs dins!',
    'player.greeting': 'Hola, {name}',
    'player.waitingLabel': 'Esperant a l\\'amfitrió...',
    'player.getReady': 'Prepara\\'t!',
    'player.nextQuestionLabel': 'Properament...',
    'player.sent': 'Resposta enviada!',
    'player.waitingOthers': 'Esperant...',
    'player.correct': 'Correcte!',
    'player.incorrect': 'Incorrecte',
    'player.streak': 'Ratxa',
    'player.leaderboard': 'Classificació',
    'player.rank': 'Posició',
    'player.waitingNext': 'Esperant...',
    'player.gameEnded': 'Fí!',
    'player.finalRank': 'Posició final',
    'editor.quizTitle': 'Títol',
    'editor.addQuestion': '➕ Afegir',
    'editor.question': 'Pregunta',
    'editor.removeQuestion': 'Eliminar',
    'editor.uploadImage': '📷 Imatge',
    'editor.removeImage': '❌ Treure',
    'editor.timeLimit': 'Temps',
    'editor.imageUrl': 'URL...',
    'editor.noImage': 'Sense imatge',
    'editor.imagePreviewAlt': 'Vista prèvia',
    'editor.answerPlaceholder': 'Resposta {number}'
};

const eu = {
    'app.title': 'Preguntador',
    'app.subtitle': 'Sortu galdetegiak eta jolastu lagunekin',
    'app.pageTitle': 'Preguntador | Zuzeneko galdetegiak',
    'app.pageDescription': 'Backend gabeko jokoa.',
    'app.repository': 'Biltegia',
    'language.es': 'Espainiera',
    'language.en': 'Ingelesa',
    'language.gl': 'Galegoa',
    'language.fr': 'Frantsesa',
    'language.de': 'Alemana',
    'language.pt': 'Portugesa',
    'language.ca': 'Katalana',
    'language.eu': 'Euskara',
    'home.createQuiz': '✏️ Sortu berria',
    'home.importQuiz': '📥 Inportatu',
    'home.joinGame': '🎮 Sartu jokoan',
    'home.myQuizzes': '📚 Nire galdetegiak',
    'home.questions': 'galderak',
    'home.question': 'galdera',
    'home.play': 'Jokatu',
    'home.edit': 'Editatu',
    'home.export': 'Esportatu',
    'home.delete': 'Ezabatu',
    'home.deleteConfirm': 'Ezabatu galdetegia?',
    'home.importError': 'Ezin inportatu.',
    'home.chatgptPrompt': 'IA bidez sortu',
    'home.invalidQuizTitle': 'Osatu galdetegia',
    'home.aiTitle': 'IA bidez',
    'home.aiStep1': '1. Kopia ezazu.',
    'home.aiStep2': '2. Itsatsi JSONa:',
    'home.aiCopy': '📋 Kopiatu',
    'home.aiCopied': '✅ Kopiatua',
    'home.aiCreate': '✨ Sortu',
    'home.aiPlaceholder': '{"title": "Galdetegia", "questions": [...]}',
    'home.aiJsonError': 'JSON baliogabea.',
    'home.aiPromptTemplate': `Sortu galdetegi JSON bat: [TEMA_AQUI]. \n{  "title": "Izenburua",  "questions": [ { "text": "...", "timeLimit": 20, "image": "", "answers": [ { "text": "Aukera", "correct": false }, { "text": "Zuzena", "correct": true } ] } ] }`,
    'join.title': 'Sartu jokoan',
    'join.codeLabel': 'Gela kodea',
    'join.nameLabel': 'Zure izena',
    'join.codePlaceholder': 'ABC123',
    'join.namePlaceholder': 'Izena',
    'join.connecting': '⏳ Konektatzen...',
    'join.connected': 'Konektatuta!',
    'join.joinBtn': '🚀 Sartu',
    'join.backBtn': '← Itzuli',
    'join.errorPrefix': 'Errorea',
    'join.errorInvalidCode': 'Sarrera ukatu da.',
    'join.errorRejected': 'Bukatuta.',
    'join.errorGameInProgress': 'Jokoa hasita dago.',
    'join.errorConnectionClosed': 'Konexioa itxita.',
    'join.errorTimeout': 'Denbora agortuta.',
    'join.errorUnknown': 'Ezezaguna.',
    'lobby.roomCode': 'Kodea',
    'lobby.players': 'Jokalariak',
    'lobby.waiting': 'Itxaroten...',
    'lobby.startBtn': '▶ Hasi',
    'lobby.backBtn': '← Atera',
    'lobby.joinHint': 'Eskaneatu: {url}',
    'lobby.errorMissingQuiz': 'Ez da aurkitu.',
    'lobby.errorInvalidQuiz': 'Osatu beharra.',
    'lobby.errorGeneric': 'Errorea.',
    'game.ready': 'Prest...',
    'game.go': 'Orain!',
    'game.answers': 'erantzun',
    'game.results': 'Emaitzak',
    'game.points': 'puntu',
    'game.next': 'Hurrengoa →',
    'game.finalResults': 'Emaitza finalak',
    'game.nextQuestion': 'Hurrengo galdera →',
    'game.questionCounter': 'Galdera {current} / {total}',
    'game.questionImageAlt': 'Irudia',
    'player.disconnectedTitle': 'Itxita',
    'player.disconnectedSub': 'Ostalarirekin konexioa galduta',
    'player.in': 'Barruan zaude!',
    'player.greeting': 'Kaixo, {name}',
    'player.waitingLabel': 'Itxaroten ostalariari...',
    'player.getReady': 'Prest egon!',
    'player.nextQuestionLabel': 'Hurrengoa...',
    'player.sent': 'Bidalita!',
    'player.waitingOthers': 'Besteen zain...',
    'player.correct': 'Zuzena!',
    'player.incorrect': 'Okerra',
    'player.streak': 'Bolada',
    'player.leaderboard': 'Sailkapena',
    'player.rank': 'Postua',
    'player.waitingNext': 'Itxaroten...',
    'player.gameEnded': 'Amaiera!',
    'player.finalRank': 'Postu finala',
    'editor.quizTitle': 'Izenburua',
    'editor.addQuestion': '➕ Gehitu',
    'editor.question': 'Galdera',
    'editor.removeQuestion': 'Ezabatu',
    'editor.uploadImage': '📷 Irudia',
    'editor.removeImage': '❌ Kendu',
    'editor.timeLimit': 'Denbora',
    'editor.imageUrl': 'URL...',
    'editor.noImage': 'Gabe',
    'editor.imagePreviewAlt': 'Irudia',
    'editor.answerPlaceholder': 'Erantzuna {number}'
};

const pt = {
    'app.title': 'Preguntador',
    'app.subtitle': 'Crie quizzes e jogue em tempo real',
    'app.pageTitle': 'Preguntador | Quiz ao vivo',
    'app.pageDescription': 'Quiz em tempo real sem backend.',
    'app.repository': 'Repositório',
    'language.es': 'Espanhol',
    'language.en': 'Inglês',
    'language.gl': 'Galego',
    'language.fr': 'Francês',
    'language.de': 'Alemão',
    'language.pt': 'Português',
    'language.ca': 'Catalão',
    'language.eu': 'Basco',
    'home.createQuiz': '✏️ Criar novo quiz',
    'home.importQuiz': '📥 Importar quiz',
    'home.joinGame': '🎮 Entrar na partida',
    'home.myQuizzes': '📚 Meus quizzes',
    'home.questions': 'perguntas',
    'home.question': 'pergunta',
    'home.play': 'Jogar',
    'home.edit': 'Editar',
    'home.export': 'Explorar',
    'home.delete': 'Excluir',
    'home.deleteConfirm': 'Excluir quiz?',
    'home.importError': 'Erro ao importar.',
    'home.chatgptPrompt': 'Gerar com IA',
    'home.invalidQuizTitle': 'Complete o quiz antes',
    'home.aiTitle': 'Gerar com IA',
    'home.aiStep1': '1. Copie e peça ao ChatGPT.',
    'home.aiStep2': '2. Cole o JSON aqui:',
    'home.aiCopy': '📋 Copiar',
    'home.aiCopied': '✅ Copiado',
    'home.aiCreate': '✨ Criar',
    'home.aiPlaceholder': '{"title": "Novo Quiz", "questions": [...]}',
    'home.aiJsonError': 'Erro de formato JSON.',
    'home.aiPromptTemplate': `Gere JSON de trivia: [TEMA_AQUI]. \n{  "title": "Titulo",  "questions": [ { "text": "...", "timeLimit": 20, "image": "", "answers": [ { "text": "Op", "correct": false }, { "text": "Corr", "correct": true } ] } ] }`,
    'join.title': 'Entrar',
    'join.codeLabel': 'Código',
    'join.nameLabel': 'Seu nome',
    'join.codePlaceholder': 'ABC123',
    'join.namePlaceholder': 'Seu nome',
    'join.connecting': '⏳ Conectando...',
    'join.connected': 'Conectado!',
    'join.joinBtn': '🚀 Entrar',
    'join.backBtn': '← Voltar',
    'join.errorPrefix': 'Erro',
    'join.errorInvalidCode': 'Código inválido.',
    'join.errorRejected': 'Rejeitado.',
    'join.errorGameInProgress': 'Jogo em andamento.',
    'join.errorConnectionClosed': 'Conexão fechada.',
    'join.errorTimeout': 'Tempo excedido.',
    'join.errorUnknown': 'Erro desconhecido.',
    'lobby.roomCode': 'Código',
    'lobby.players': 'Jogadores',
    'lobby.waiting': 'Aguardando...',
    'lobby.startBtn': '▶ Iniciar',
    'lobby.backBtn': '← Sair',
    'lobby.joinHint': 'Acesse: {url}',
    'lobby.errorMissingQuiz': 'Quiz não encontrado.',
    'lobby.errorInvalidQuiz': 'Quiz incompleto.',
    'lobby.errorGeneric': 'Erro ao abrir sala',
    'game.ready': 'Pronto...',
    'game.go': 'Vai!',
    'game.answers': 'respostas',
    'game.results': 'Resultados',
    'game.points': 'pontos',
    'game.next': 'Próximo →',
    'game.finalResults': 'Resultados Finais',
    'game.nextQuestion': 'Próxima →',
    'game.questionCounter': 'Pergunta {current} / {total}',
    'game.questionImageAlt': 'Imagem',
    'player.disconnectedTitle': 'Desconectado',
    'player.disconnectedSub': 'Conexão perdida',
    'player.in': 'Você entrou!',
    'player.greeting': 'Olá, {name}',
    'player.waitingLabel': 'Aguardando...',
    'player.getReady': 'Prepare-se!',
    'player.nextQuestionLabel': 'Próxima pergunta...',
    'player.sent': 'Enviado!',
    'player.waitingOthers': 'Aguardando outros...',
    'player.correct': 'Correto!',
    'player.incorrect': 'Incorreto',
    'player.streak': 'Série',
    'player.leaderboard': 'Placar',
    'player.rank': 'Sua posição',
    'player.waitingNext': 'Aguardando...',
    'player.gameEnded': 'Fim!',
    'player.finalRank': 'Posição final',
    'editor.quizTitle': 'Título',
    'editor.addQuestion': '➕ Adicionar',
    'editor.question': 'Pergunta',
    'editor.removeQuestion': 'Remover',
    'editor.uploadImage': '📷 Imagem',
    'editor.removeImage': '❌ Remover',
    'editor.timeLimit': 'Tempo',
    'editor.imageUrl': 'URL...',
    'editor.noImage': 'Sem imagem',
    'editor.imagePreviewAlt': 'Preview',
    'editor.answerPlaceholder': 'Resposta {number}'
};

const fr = {
    'app.title': 'Preguntador',
    'app.subtitle': 'Créez vos quiz et jouez en direct',
    'app.pageTitle': 'Preguntador | Quiz',
    'app.pageDescription': 'Jeu de quiz en temps réel sans backend.',
    'app.repository': 'Dépôt',
    'language.es': 'Espagnol',
    'language.en': 'Anglais',
    'language.gl': 'Galicien',
    'language.fr': 'Français',
    'language.de': 'Allemand',
    'language.pt': 'Portugais',
    'language.ca': 'Catalan',
    'language.eu': 'Basque',
    'home.createQuiz': '✏️ Nouveau quiz',
    'home.importQuiz': '📥 Importer',
    'home.joinGame': '🎮 Rejoindre',
    'home.myQuizzes': '📚 Mes quiz',
    'home.questions': 'questions',
    'home.question': 'question',
    'home.play': 'Jouer',
    'home.edit': 'Modifier',
    'home.export': 'Exporter',
    'home.delete': 'Supprimer',
    'home.deleteConfirm': 'Supprimer ?',
    'home.importError': 'Erreur.',
    'home.chatgptPrompt': 'Générer avec IA',
    'home.invalidQuizTitle': 'Complétez le quiz',
    'home.aiTitle': 'Générer',
    'home.aiStep1': '1. Copiez et demandez à l\\'IA.',
    'home.aiStep2': '2. Collez le JSON:',
    'home.aiCopy': '📋 Copier',
    'home.aiCopied': '✅ Copié',
    'home.aiCreate': '✨ Créer',
    'home.aiPlaceholder': '{"title": "Nouveau", "questions": [...]}',
    'home.aiJsonError': 'JSON invalide.',
    'home.aiPromptTemplate': `Génère un JSON : [TEMA_AQUI]. \n{  "title": "Titre",  "questions": [ { "text": "...", "timeLimit": 20, "image": "", "answers": [ { "text": "Op", "correct": false }, { "text": "Corr", "correct": true } ] } ] }`,
    'join.title': 'Rejoindre',
    'join.codeLabel': 'Code',
    'join.nameLabel': 'Nom',
    'join.codePlaceholder': 'ABC123',
    'join.namePlaceholder': 'Nom',
    'join.connecting': '⏳ Connexion...',
    'join.connected': 'Connecté !',
    'join.joinBtn': '🚀 Rejoindre',
    'join.backBtn': '← Retour',
    'join.errorPrefix': 'Erreur',
    'join.errorInvalidCode': 'Code invalide.',
    'join.errorRejected': 'Rejeté.',
    'join.errorGameInProgress': 'En cours.',
    'join.errorConnectionClosed': 'Bloqué.',
    'join.errorTimeout': 'Délai dépassé.',
    'join.errorUnknown': 'Inconnu.',
    'lobby.roomCode': 'Code',
    'lobby.players': 'Joueurs',
    'lobby.waiting': 'Attente...',
    'lobby.startBtn': '▶ Démarrer',
    'lobby.backBtn': '← Quitter',
    'lobby.joinHint': 'Ouvrez : {url}',
    'lobby.errorMissingQuiz': 'Non trouvé.',
    'lobby.errorInvalidQuiz': 'Incomplet.',
    'lobby.errorGeneric': 'Erreur',
    'game.ready': 'Prêts...',
    'game.go': 'Partez !',
    'game.answers': 'réponses',
    'game.results': 'Résultats',
    'game.points': 'points',
    'game.next': 'Suivant →',
    'game.finalResults': 'Score final',
    'game.nextQuestion': 'Question suivante →',
    'game.questionCounter': 'Question {current} / {total}',
    'game.questionImageAlt': 'Image',
    'player.disconnectedTitle': 'Déconnecté',
    'player.disconnectedSub': 'Connexion perdue',
    'player.in': 'Vous y êtes !',
    'player.greeting': 'Salut, {name}',
    'player.waitingLabel': 'Attente...',
    'player.getReady': 'C\\'est parti !',
    'player.nextQuestionLabel': 'Ensuite...',
    'player.sent': 'Envoyé !',
    'player.waitingOthers': 'Attente des autres...',
    'player.correct': 'Correct !',
    'player.incorrect': 'Faux',
    'player.streak': 'Série',
    'player.leaderboard': 'Classement',
    'player.rank': 'Position',
    'player.waitingNext': 'Attente...',
    'player.gameEnded': 'Fin !',
    'player.finalRank': 'Rang final',
    'editor.quizTitle': 'Titre',
    'editor.addQuestion': '➕ Ajouter',
    'editor.question': 'Question',
    'editor.removeQuestion': 'Retirer',
    'editor.uploadImage': '📷 Image',
    'editor.removeImage': '❌ Retirer',
    'editor.timeLimit': 'Temps',
    'editor.imageUrl': 'URL...',
    'editor.noImage': 'Pas d\\'image',
    'editor.imagePreviewAlt': 'Aperçu',
    'editor.answerPlaceholder': 'Réponse {number}'
};

const de = {
    'app.title': 'Preguntador',
    'app.subtitle': 'Erstelle Quizzes und spiele in Echtzeit',
    'app.pageTitle': 'Preguntador | Live Quiz',
    'app.pageDescription': 'Echtzeit-Quiz ohne Backend.',
    'app.repository': 'Repository',
    'language.es': 'Spanisch',
    'language.en': 'Englisch',
    'language.gl': 'Galizisch',
    'language.fr': 'Französisch',
    'language.de': 'Deutsch',
    'language.pt': 'Portugiesisch',
    'language.ca': 'Katalanisch',
    'language.eu': 'Baskisch',
    'home.createQuiz': '✏️ Neues Quiz',
    'home.importQuiz': '📥 Importieren',
    'home.joinGame': '🎮 Beitreten',
    'home.myQuizzes': '📚 Meine Quizzes',
    'home.questions': 'Fragen',
    'home.question': 'Frage',
    'home.play': 'Spielen',
    'home.edit': 'Bearbeiten',
    'home.export': 'Exportieren',
    'home.delete': 'Löschen',
    'home.deleteConfirm': 'Löschen?',
    'home.importError': 'Fehler.',
    'home.chatgptPrompt': 'Mit KI generieren',
    'home.invalidQuizTitle': 'Quiz vervollständigen',
    'home.aiTitle': 'KI Generierung',
    'home.aiStep1': '1. Kopieren.',
    'home.aiStep2': '2. JSON hier einfügen:',
    'home.aiCopy': '📋 Kopieren',
    'home.aiCopied': '✅ Kopiert',
    'home.aiCreate': '✨ Erstellen',
    'home.aiPlaceholder': '{"title": "Neues Quiz", "questions": [...]}',
    'home.aiJsonError': 'Ungültiges JSON.',
    'home.aiPromptTemplate': `Erstelle ein JSON : [THEMA]. \n{  "title": "Titel",  "questions": [ { "text": "...", "timeLimit": 20, "image": "", "answers": [ { "text": "Op", "correct": false }, { "text": "Korr", "correct": true } ] } ] }`,
    'join.title': 'Beitreten',
    'join.codeLabel': 'Code',
    'join.nameLabel': 'Name',
    'join.codePlaceholder': 'ABC123',
    'join.namePlaceholder': 'Name',
    'join.connecting': '⏳ Verbinden...',
    'join.connected': 'Verbunden!',
    'join.joinBtn': '🚀 Beitreten',
    'join.backBtn': '← Zurück',
    'join.errorPrefix': 'Fehler',
    'join.errorInvalidCode': 'Ungültiger Code.',
    'join.errorRejected': 'Abgelehnt.',
    'join.errorGameInProgress': 'Spiel läuft bereits.',
    'join.errorConnectionClosed': 'Geschlossen.',
    'join.errorTimeout': 'Zeitüberschreitung.',
    'join.errorUnknown': 'Unbekannt.',
    'lobby.roomCode': 'Code',
    'lobby.players': 'Spieler',
    'lobby.waiting': 'Warten...',
    'lobby.startBtn': '▶ Start',
    'lobby.backBtn': '← Verlassen',
    'lobby.joinHint': 'Öffne : {url}',
    'lobby.errorMissingQuiz': 'Nicht gefunden.',
    'lobby.errorInvalidQuiz': 'Unvollständig.',
    'lobby.errorGeneric': 'Fehler',
    'game.ready': 'Bereit...',
    'game.go': 'Los!',
    'game.answers': 'Antworten',
    'game.results': 'Ergebnisse',
    'game.points': 'Punkte',
    'game.next': 'Weiter →',
    'game.finalResults': 'Endergebnis',
    'game.nextQuestion': 'Nächste Frage →',
    'game.questionCounter': 'Frage {current} / {total}',
    'game.questionImageAlt': 'Bild',
    'player.disconnectedTitle': 'Getrennt',
    'player.disconnectedSub': 'Verbindung verloren',
    'player.in': 'Du bist drin!',
    'player.greeting': 'Hallo, {name}',
    'player.waitingLabel': 'Warten...',
    'player.getReady': 'Mach dich bereit!',
    'player.nextQuestionLabel': 'Gleich geht\\'s weiter...',
    'player.sent': 'Gesendet!',
    'player.waitingOthers': 'Warten auf die anderen...',
    'player.correct': 'Richtig!',
    'player.incorrect': 'Falsch',
    'player.streak': 'Serie',
    'player.leaderboard': 'Bestenliste',
    'player.rank': 'Dein Platz',
    'player.waitingNext': 'Warten...',
    'player.gameEnded': 'Ende!',
    'player.finalRank': 'Endplatzierung',
    'editor.quizTitle': 'Titel',
    'editor.addQuestion': '➕ Hinzufügen',
    'editor.question': 'Frage',
    'editor.removeQuestion': 'Entfernen',
    'editor.uploadImage': '📷 Bild',
    'editor.removeImage': '❌ Entfernen',
    'editor.timeLimit': 'Zeitlimit',
    'editor.imageUrl': 'URL...',
    'editor.noImage': 'Kein Bild',
    'editor.imagePreviewAlt': 'Vorschau',
    'editor.answerPlaceholder': 'Antwort {number}'
};

const text = fs.readFileSync('src/i18n.jsx', 'utf-8');

// Add translation options to the es, en, gl blocks
let result = text.replace(/'language\\.gl': 'Galego',/g, 
\`'language.gl': 'Galego',
        'language.ca': 'Català',
        'language.eu': 'Euskara',
        'language.pt': 'Português',
        'language.fr': 'Français',
        'language.de': 'Deutsch',\`);

result = result.replace(/'language\\.gl': 'Galician',/g, 
\`'language.gl': 'Galician',
        'language.ca': 'Catalan',
        'language.eu': 'Basque',
        'language.pt': 'Portuguese',
        'language.fr': 'French',
        'language.de': 'German',\`);

// Append the new translations before the closing }; of the object
const injectIndex = result.lastIndexOf('};');

const newContent = 
\`    ca: \${JSON.stringify(ca, null, 8).replace(/\}$/, '    }')},
    eu: \${JSON.stringify(eu, null, 8).replace(/\}$/, '    }')},
    pt: \${JSON.stringify(pt, null, 8).replace(/\}$/, '    }')},
    fr: \${JSON.stringify(fr, null, 8).replace(/\}$/, '    }')},
    de: \${JSON.stringify(de, null, 8).replace(/\}$/, '    }')}
\`;

result = result.substring(0, injectIndex) + newContent + result.substring(injectIndex);

fs.writeFileSync('src/i18n.jsx', result);
console.log('Done mapping.');
